### PR TITLE
Add: support reminder when creating tasks from GUI

### PR DESCRIPTION
**Pull request by eight04**
Changes:

1. Add a reminder prompt to task creation GUI.
2. Tasks in the GUI are sorted by reminder, due date, and created date.
3. <del>I removed created date from the GUI since I don't need them.</del>

### CODE REVIEW

**Comment by kiblee** [comment]
Hi @eight04 . Thanks for the PR! Regarding no. 3 in your changes:

> I removed created date from the GUI since I don't need them.

Other users may need Created Date - it's useful information. Is there any other reason you decided to remove it? If not, can you revert this change?

**Comment by eight04** [comment]
I'll revert it later, but the UI looks cleaner with the change:
image

Other ideas to improve the UI:

1. Use 2 columns for created date and reminder.
2. Improve how the time is displayed e.g. `2024-01-05 17:00` => `1h24m` when the reminder < 24h

**Comment by eight04** [comment]
Compare to the original UI:
image

**Review by kiblee — APPROVED** [review]

**Comment by kiblee** [comment]
Those are good ideas. I agree it is rather cluttered with both dates but it's too early to remove them for now. Let's decide on a better approach.

**Pull request merged**
